# Generated by Django 4.2 on 2024-04-23 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=30000)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2024, 4, 23, 18, 19, 42, 136757, tzinfo=datetime.timezone.utc))),
                ('draft', models.BooleanField(default=True)),
            ],
        ),
    ]
